#!/bin/bash

# opdraw/script
# Copyright (c) 2021 J. M. Spivey

density=300;                    # Pixels per inch for PNG output
colour=-c;                      # Use -c to colour the ovals

if [ $# -lt 1 ]; then echo Usage: opdraw file.op; exit 1; fi

input=$1
fname=$(basename $input .op)
tex="\\input opdraw2 \\shipout\\vbox{\\input $fname.mtx } \\bye"

set -x

./opdraw $colour $input >$fname.mp \
    && mpost $fname.mp \
    && ./mp2pdf $fname.1 >$fname.mtx \
    && echo -E $tex >$fname.tex \
    && pdftex $fname.tex \
    && pdftocairo -singlefile -png -r $density $fname.pdf $fname \
    && pdftocairo -svg $fname.pdf $fname.svg
